// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef PROTOBUF_protocol_2eproto__INCLUDED
#define PROTOBUF_protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "keys.pb.h"
// @@protoc_insertion_point(includes)

namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protocol_2eproto();
void protobuf_AssignDesc_protocol_2eproto();
void protobuf_ShutdownFile_protocol_2eproto();

class AppDestroyed;
class AppGotFocus;
class AppList;
class Application;
class Event;
class Icon;
class KeystrokeRequest;
class Response;

enum Response_Status {
  Response_Status_Success = 1,
  Response_Status_WindowLostFocus = 2
};
bool Response_Status_IsValid(int value);
const Response_Status Response_Status_Status_MIN = Response_Status_Success;
const Response_Status Response_Status_Status_MAX = Response_Status_WindowLostFocus;
const int Response_Status_Status_ARRAYSIZE = Response_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* Response_Status_descriptor();
inline const ::std::string& Response_Status_Name(Response_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    Response_Status_descriptor(), value);
}
inline bool Response_Status_Parse(
    const ::std::string& name, Response_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Response_Status>(
    Response_Status_descriptor(), name, value);
}
// ===================================================================

class KeystrokeRequest : public ::google::protobuf::Message {
 public:
  KeystrokeRequest();
  virtual ~KeystrokeRequest();

  KeystrokeRequest(const KeystrokeRequest& from);

  inline KeystrokeRequest& operator=(const KeystrokeRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeystrokeRequest& default_instance();

  void Swap(KeystrokeRequest* other);

  // implements Message ----------------------------------------------

  inline KeystrokeRequest* New() const { return New(NULL); }

  KeystrokeRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeystrokeRequest& from);
  void MergeFrom(const KeystrokeRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KeystrokeRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 req_id = 7;
  bool has_req_id() const;
  void clear_req_id();
  static const int kReqIdFieldNumber = 7;
  ::google::protobuf::uint32 req_id() const;
  void set_req_id(::google::protobuf::uint32 value);

  // required uint64 app_id = 1;
  bool has_app_id() const;
  void clear_app_id();
  static const int kAppIdFieldNumber = 1;
  ::google::protobuf::uint64 app_id() const;
  void set_app_id(::google::protobuf::uint64 value);

  // required bool ctrl = 2;
  bool has_ctrl() const;
  void clear_ctrl();
  static const int kCtrlFieldNumber = 2;
  bool ctrl() const;
  void set_ctrl(bool value);

  // required bool alt = 3;
  bool has_alt() const;
  void clear_alt();
  static const int kAltFieldNumber = 3;
  bool alt() const;
  void set_alt(bool value);

  // required bool shift = 4;
  bool has_shift() const;
  void clear_shift();
  static const int kShiftFieldNumber = 4;
  bool shift() const;
  void set_shift(bool value);

  // required bool meta = 5;
  bool has_meta() const;
  void clear_meta();
  static const int kMetaFieldNumber = 5;
  bool meta() const;
  void set_meta(bool value);

  // required .msgs.Keycode key = 6;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 6;
  ::msgs::Keycode key() const;
  void set_key(::msgs::Keycode value);

  // @@protoc_insertion_point(class_scope:msgs.KeystrokeRequest)
 private:
  inline void set_has_req_id();
  inline void clear_has_req_id();
  inline void set_has_app_id();
  inline void clear_has_app_id();
  inline void set_has_ctrl();
  inline void clear_has_ctrl();
  inline void set_has_alt();
  inline void clear_has_alt();
  inline void set_has_shift();
  inline void clear_has_shift();
  inline void set_has_meta();
  inline void clear_has_meta();
  inline void set_has_key();
  inline void clear_has_key();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 app_id_;
  ::google::protobuf::uint32 req_id_;
  bool ctrl_;
  bool alt_;
  bool shift_;
  bool meta_;
  int key_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static KeystrokeRequest* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  inline Response* New() const { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_Status Status;
  static const Status Success =
    Response_Status_Success;
  static const Status WindowLostFocus =
    Response_Status_WindowLostFocus;
  static inline bool Status_IsValid(int value) {
    return Response_Status_IsValid(value);
  }
  static const Status Status_MIN =
    Response_Status_Status_MIN;
  static const Status Status_MAX =
    Response_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    Response_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return Response_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return Response_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return Response_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint32 req_id = 1;
  bool has_req_id() const;
  void clear_req_id();
  static const int kReqIdFieldNumber = 1;
  ::google::protobuf::uint32 req_id() const;
  void set_req_id(::google::protobuf::uint32 value);

  // required .msgs.Response.Status status = 2;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::msgs::Response_Status status() const;
  void set_status(::msgs::Response_Status value);

  // @@protoc_insertion_point(class_scope:msgs.Response)
 private:
  inline void set_has_req_id();
  inline void clear_has_req_id();
  inline void set_has_status();
  inline void clear_has_status();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 req_id_;
  int status_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// -------------------------------------------------------------------

class AppList : public ::google::protobuf::Message {
 public:
  AppList();
  virtual ~AppList();

  AppList(const AppList& from);

  inline AppList& operator=(const AppList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppList& default_instance();

  void Swap(AppList* other);

  // implements Message ----------------------------------------------

  inline AppList* New() const { return New(NULL); }

  AppList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppList& from);
  void MergeFrom(const AppList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AppList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .msgs.Application apps = 1;
  int apps_size() const;
  void clear_apps();
  static const int kAppsFieldNumber = 1;
  const ::msgs::Application& apps(int index) const;
  ::msgs::Application* mutable_apps(int index);
  ::msgs::Application* add_apps();
  ::google::protobuf::RepeatedPtrField< ::msgs::Application >*
      mutable_apps();
  const ::google::protobuf::RepeatedPtrField< ::msgs::Application >&
      apps() const;

  // @@protoc_insertion_point(class_scope:msgs.AppList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::msgs::Application > apps_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static AppList* default_instance_;
};
// -------------------------------------------------------------------

class Application : public ::google::protobuf::Message {
 public:
  Application();
  virtual ~Application();

  Application(const Application& from);

  inline Application& operator=(const Application& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Application& default_instance();

  void Swap(Application* other);

  // implements Message ----------------------------------------------

  inline Application* New() const { return New(NULL); }

  Application* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Application& from);
  void MergeFrom(const Application& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Application* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string win_title = 3;
  bool has_win_title() const;
  void clear_win_title();
  static const int kWinTitleFieldNumber = 3;
  const ::std::string& win_title() const;
  void set_win_title(const ::std::string& value);
  void set_win_title(const char* value);
  void set_win_title(const char* value, size_t size);
  ::std::string* mutable_win_title();
  ::std::string* release_win_title();
  void set_allocated_win_title(::std::string* win_title);

  // optional .msgs.Icon icon = 4;
  bool has_icon() const;
  void clear_icon();
  static const int kIconFieldNumber = 4;
  const ::msgs::Icon& icon() const;
  ::msgs::Icon* mutable_icon();
  ::msgs::Icon* release_icon();
  void set_allocated_icon(::msgs::Icon* icon);

  // @@protoc_insertion_point(class_scope:msgs.Application)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_win_title();
  inline void clear_has_win_title();
  inline void set_has_icon();
  inline void clear_has_icon();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr win_title_;
  ::msgs::Icon* icon_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Application* default_instance_;
};
// -------------------------------------------------------------------

class Icon : public ::google::protobuf::Message {
 public:
  Icon();
  virtual ~Icon();

  Icon(const Icon& from);

  inline Icon& operator=(const Icon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Icon& default_instance();

  void Swap(Icon* other);

  // implements Message ----------------------------------------------

  inline Icon* New() const { return New(NULL); }

  Icon* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Icon& from);
  void MergeFrom(const Icon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Icon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 width = 1;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // required uint32 height = 2;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // required bytes pixels = 3;
  bool has_pixels() const;
  void clear_pixels();
  static const int kPixelsFieldNumber = 3;
  const ::std::string& pixels() const;
  void set_pixels(const ::std::string& value);
  void set_pixels(const char* value);
  void set_pixels(const void* value, size_t size);
  ::std::string* mutable_pixels();
  ::std::string* release_pixels();
  void set_allocated_pixels(::std::string* pixels);

  // @@protoc_insertion_point(class_scope:msgs.Icon)
 private:
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_pixels();
  inline void clear_has_pixels();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::internal::ArenaStringPtr pixels_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Icon* default_instance_;
};
// -------------------------------------------------------------------

class AppDestroyed : public ::google::protobuf::Message {
 public:
  AppDestroyed();
  virtual ~AppDestroyed();

  AppDestroyed(const AppDestroyed& from);

  inline AppDestroyed& operator=(const AppDestroyed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppDestroyed& default_instance();

  void Swap(AppDestroyed* other);

  // implements Message ----------------------------------------------

  inline AppDestroyed* New() const { return New(NULL); }

  AppDestroyed* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppDestroyed& from);
  void MergeFrom(const AppDestroyed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AppDestroyed* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:msgs.AppDestroyed)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static AppDestroyed* default_instance_;
};
// -------------------------------------------------------------------

class AppGotFocus : public ::google::protobuf::Message {
 public:
  AppGotFocus();
  virtual ~AppGotFocus();

  AppGotFocus(const AppGotFocus& from);

  inline AppGotFocus& operator=(const AppGotFocus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppGotFocus& default_instance();

  void Swap(AppGotFocus* other);

  // implements Message ----------------------------------------------

  inline AppGotFocus* New() const { return New(NULL); }

  AppGotFocus* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppGotFocus& from);
  void MergeFrom(const AppGotFocus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AppGotFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:msgs.AppGotFocus)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static AppGotFocus* default_instance_;
};
// -------------------------------------------------------------------

class Event : public ::google::protobuf::Message {
 public:
  Event();
  virtual ~Event();

  Event(const Event& from);

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Event& default_instance();

  void Swap(Event* other);

  // implements Message ----------------------------------------------

  inline Event* New() const { return New(NULL); }

  Event* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .msgs.AppDestroyed destroyed = 1;
  bool has_destroyed() const;
  void clear_destroyed();
  static const int kDestroyedFieldNumber = 1;
  const ::msgs::AppDestroyed& destroyed() const;
  ::msgs::AppDestroyed* mutable_destroyed();
  ::msgs::AppDestroyed* release_destroyed();
  void set_allocated_destroyed(::msgs::AppDestroyed* destroyed);

  // optional .msgs.Application created = 2;
  bool has_created() const;
  void clear_created();
  static const int kCreatedFieldNumber = 2;
  const ::msgs::Application& created() const;
  ::msgs::Application* mutable_created();
  ::msgs::Application* release_created();
  void set_allocated_created(::msgs::Application* created);

  // optional .msgs.AppGotFocus got_focus = 3;
  bool has_got_focus() const;
  void clear_got_focus();
  static const int kGotFocusFieldNumber = 3;
  const ::msgs::AppGotFocus& got_focus() const;
  ::msgs::AppGotFocus* mutable_got_focus();
  ::msgs::AppGotFocus* release_got_focus();
  void set_allocated_got_focus(::msgs::AppGotFocus* got_focus);

  // optional .msgs.Response response = 4;
  bool has_response() const;
  void clear_response();
  static const int kResponseFieldNumber = 4;
  const ::msgs::Response& response() const;
  ::msgs::Response* mutable_response();
  ::msgs::Response* release_response();
  void set_allocated_response(::msgs::Response* response);

  // @@protoc_insertion_point(class_scope:msgs.Event)
 private:
  inline void set_has_destroyed();
  inline void clear_has_destroyed();
  inline void set_has_created();
  inline void clear_has_created();
  inline void set_has_got_focus();
  inline void clear_has_got_focus();
  inline void set_has_response();
  inline void clear_has_response();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::msgs::AppDestroyed* destroyed_;
  ::msgs::Application* created_;
  ::msgs::AppGotFocus* got_focus_;
  ::msgs::Response* response_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Event* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// KeystrokeRequest

// required uint32 req_id = 7;
inline bool KeystrokeRequest::has_req_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KeystrokeRequest::set_has_req_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KeystrokeRequest::clear_has_req_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KeystrokeRequest::clear_req_id() {
  req_id_ = 0u;
  clear_has_req_id();
}
inline ::google::protobuf::uint32 KeystrokeRequest::req_id() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.req_id)
  return req_id_;
}
inline void KeystrokeRequest::set_req_id(::google::protobuf::uint32 value) {
  set_has_req_id();
  req_id_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.req_id)
}

// required uint64 app_id = 1;
inline bool KeystrokeRequest::has_app_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KeystrokeRequest::set_has_app_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void KeystrokeRequest::clear_has_app_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void KeystrokeRequest::clear_app_id() {
  app_id_ = GOOGLE_ULONGLONG(0);
  clear_has_app_id();
}
inline ::google::protobuf::uint64 KeystrokeRequest::app_id() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.app_id)
  return app_id_;
}
inline void KeystrokeRequest::set_app_id(::google::protobuf::uint64 value) {
  set_has_app_id();
  app_id_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.app_id)
}

// required bool ctrl = 2;
inline bool KeystrokeRequest::has_ctrl() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void KeystrokeRequest::set_has_ctrl() {
  _has_bits_[0] |= 0x00000004u;
}
inline void KeystrokeRequest::clear_has_ctrl() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void KeystrokeRequest::clear_ctrl() {
  ctrl_ = false;
  clear_has_ctrl();
}
inline bool KeystrokeRequest::ctrl() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.ctrl)
  return ctrl_;
}
inline void KeystrokeRequest::set_ctrl(bool value) {
  set_has_ctrl();
  ctrl_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.ctrl)
}

// required bool alt = 3;
inline bool KeystrokeRequest::has_alt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void KeystrokeRequest::set_has_alt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void KeystrokeRequest::clear_has_alt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void KeystrokeRequest::clear_alt() {
  alt_ = false;
  clear_has_alt();
}
inline bool KeystrokeRequest::alt() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.alt)
  return alt_;
}
inline void KeystrokeRequest::set_alt(bool value) {
  set_has_alt();
  alt_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.alt)
}

// required bool shift = 4;
inline bool KeystrokeRequest::has_shift() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void KeystrokeRequest::set_has_shift() {
  _has_bits_[0] |= 0x00000010u;
}
inline void KeystrokeRequest::clear_has_shift() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void KeystrokeRequest::clear_shift() {
  shift_ = false;
  clear_has_shift();
}
inline bool KeystrokeRequest::shift() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.shift)
  return shift_;
}
inline void KeystrokeRequest::set_shift(bool value) {
  set_has_shift();
  shift_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.shift)
}

// required bool meta = 5;
inline bool KeystrokeRequest::has_meta() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void KeystrokeRequest::set_has_meta() {
  _has_bits_[0] |= 0x00000020u;
}
inline void KeystrokeRequest::clear_has_meta() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void KeystrokeRequest::clear_meta() {
  meta_ = false;
  clear_has_meta();
}
inline bool KeystrokeRequest::meta() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.meta)
  return meta_;
}
inline void KeystrokeRequest::set_meta(bool value) {
  set_has_meta();
  meta_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.meta)
}

// required .msgs.Keycode key = 6;
inline bool KeystrokeRequest::has_key() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void KeystrokeRequest::set_has_key() {
  _has_bits_[0] |= 0x00000040u;
}
inline void KeystrokeRequest::clear_has_key() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void KeystrokeRequest::clear_key() {
  key_ = 0;
  clear_has_key();
}
inline ::msgs::Keycode KeystrokeRequest::key() const {
  // @@protoc_insertion_point(field_get:msgs.KeystrokeRequest.key)
  return static_cast< ::msgs::Keycode >(key_);
}
inline void KeystrokeRequest::set_key(::msgs::Keycode value) {
  assert(::msgs::Keycode_IsValid(value));
  set_has_key();
  key_ = value;
  // @@protoc_insertion_point(field_set:msgs.KeystrokeRequest.key)
}

// -------------------------------------------------------------------

// Response

// required uint32 req_id = 1;
inline bool Response::has_req_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_req_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_req_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_req_id() {
  req_id_ = 0u;
  clear_has_req_id();
}
inline ::google::protobuf::uint32 Response::req_id() const {
  // @@protoc_insertion_point(field_get:msgs.Response.req_id)
  return req_id_;
}
inline void Response::set_req_id(::google::protobuf::uint32 value) {
  set_has_req_id();
  req_id_ = value;
  // @@protoc_insertion_point(field_set:msgs.Response.req_id)
}

// required .msgs.Response.Status status = 2;
inline bool Response::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_status() {
  status_ = 1;
  clear_has_status();
}
inline ::msgs::Response_Status Response::status() const {
  // @@protoc_insertion_point(field_get:msgs.Response.status)
  return static_cast< ::msgs::Response_Status >(status_);
}
inline void Response::set_status(::msgs::Response_Status value) {
  assert(::msgs::Response_Status_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:msgs.Response.status)
}

// -------------------------------------------------------------------

// AppList

// repeated .msgs.Application apps = 1;
inline int AppList::apps_size() const {
  return apps_.size();
}
inline void AppList::clear_apps() {
  apps_.Clear();
}
inline const ::msgs::Application& AppList::apps(int index) const {
  // @@protoc_insertion_point(field_get:msgs.AppList.apps)
  return apps_.Get(index);
}
inline ::msgs::Application* AppList::mutable_apps(int index) {
  // @@protoc_insertion_point(field_mutable:msgs.AppList.apps)
  return apps_.Mutable(index);
}
inline ::msgs::Application* AppList::add_apps() {
  // @@protoc_insertion_point(field_add:msgs.AppList.apps)
  return apps_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::msgs::Application >*
AppList::mutable_apps() {
  // @@protoc_insertion_point(field_mutable_list:msgs.AppList.apps)
  return &apps_;
}
inline const ::google::protobuf::RepeatedPtrField< ::msgs::Application >&
AppList::apps() const {
  // @@protoc_insertion_point(field_list:msgs.AppList.apps)
  return apps_;
}

// -------------------------------------------------------------------

// Application

// required uint64 id = 1;
inline bool Application::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Application::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Application::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Application::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Application::id() const {
  // @@protoc_insertion_point(field_get:msgs.Application.id)
  return id_;
}
inline void Application::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:msgs.Application.id)
}

// optional string name = 2;
inline bool Application::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Application::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Application::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Application::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Application::name() const {
  // @@protoc_insertion_point(field_get:msgs.Application.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Application::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msgs.Application.name)
}
inline void Application::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msgs.Application.name)
}
inline void Application::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msgs.Application.name)
}
inline ::std::string* Application::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:msgs.Application.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Application::release_name() {
  // @@protoc_insertion_point(field_release:msgs.Application.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Application::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:msgs.Application.name)
}

// optional string win_title = 3;
inline bool Application::has_win_title() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Application::set_has_win_title() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Application::clear_has_win_title() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Application::clear_win_title() {
  win_title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_win_title();
}
inline const ::std::string& Application::win_title() const {
  // @@protoc_insertion_point(field_get:msgs.Application.win_title)
  return win_title_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Application::set_win_title(const ::std::string& value) {
  set_has_win_title();
  win_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msgs.Application.win_title)
}
inline void Application::set_win_title(const char* value) {
  set_has_win_title();
  win_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msgs.Application.win_title)
}
inline void Application::set_win_title(const char* value, size_t size) {
  set_has_win_title();
  win_title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msgs.Application.win_title)
}
inline ::std::string* Application::mutable_win_title() {
  set_has_win_title();
  // @@protoc_insertion_point(field_mutable:msgs.Application.win_title)
  return win_title_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Application::release_win_title() {
  // @@protoc_insertion_point(field_release:msgs.Application.win_title)
  clear_has_win_title();
  return win_title_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Application::set_allocated_win_title(::std::string* win_title) {
  if (win_title != NULL) {
    set_has_win_title();
  } else {
    clear_has_win_title();
  }
  win_title_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), win_title);
  // @@protoc_insertion_point(field_set_allocated:msgs.Application.win_title)
}

// optional .msgs.Icon icon = 4;
inline bool Application::has_icon() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Application::set_has_icon() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Application::clear_has_icon() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Application::clear_icon() {
  if (icon_ != NULL) icon_->::msgs::Icon::Clear();
  clear_has_icon();
}
inline const ::msgs::Icon& Application::icon() const {
  // @@protoc_insertion_point(field_get:msgs.Application.icon)
  return icon_ != NULL ? *icon_ : *default_instance_->icon_;
}
inline ::msgs::Icon* Application::mutable_icon() {
  set_has_icon();
  if (icon_ == NULL) {
    icon_ = new ::msgs::Icon;
  }
  // @@protoc_insertion_point(field_mutable:msgs.Application.icon)
  return icon_;
}
inline ::msgs::Icon* Application::release_icon() {
  // @@protoc_insertion_point(field_release:msgs.Application.icon)
  clear_has_icon();
  ::msgs::Icon* temp = icon_;
  icon_ = NULL;
  return temp;
}
inline void Application::set_allocated_icon(::msgs::Icon* icon) {
  delete icon_;
  icon_ = icon;
  if (icon) {
    set_has_icon();
  } else {
    clear_has_icon();
  }
  // @@protoc_insertion_point(field_set_allocated:msgs.Application.icon)
}

// -------------------------------------------------------------------

// Icon

// required uint32 width = 1;
inline bool Icon::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Icon::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Icon::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Icon::clear_width() {
  width_ = 0u;
  clear_has_width();
}
inline ::google::protobuf::uint32 Icon::width() const {
  // @@protoc_insertion_point(field_get:msgs.Icon.width)
  return width_;
}
inline void Icon::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:msgs.Icon.width)
}

// required uint32 height = 2;
inline bool Icon::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Icon::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Icon::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Icon::clear_height() {
  height_ = 0u;
  clear_has_height();
}
inline ::google::protobuf::uint32 Icon::height() const {
  // @@protoc_insertion_point(field_get:msgs.Icon.height)
  return height_;
}
inline void Icon::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:msgs.Icon.height)
}

// required bytes pixels = 3;
inline bool Icon::has_pixels() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Icon::set_has_pixels() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Icon::clear_has_pixels() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Icon::clear_pixels() {
  pixels_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pixels();
}
inline const ::std::string& Icon::pixels() const {
  // @@protoc_insertion_point(field_get:msgs.Icon.pixels)
  return pixels_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Icon::set_pixels(const ::std::string& value) {
  set_has_pixels();
  pixels_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msgs.Icon.pixels)
}
inline void Icon::set_pixels(const char* value) {
  set_has_pixels();
  pixels_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msgs.Icon.pixels)
}
inline void Icon::set_pixels(const void* value, size_t size) {
  set_has_pixels();
  pixels_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msgs.Icon.pixels)
}
inline ::std::string* Icon::mutable_pixels() {
  set_has_pixels();
  // @@protoc_insertion_point(field_mutable:msgs.Icon.pixels)
  return pixels_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Icon::release_pixels() {
  // @@protoc_insertion_point(field_release:msgs.Icon.pixels)
  clear_has_pixels();
  return pixels_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Icon::set_allocated_pixels(::std::string* pixels) {
  if (pixels != NULL) {
    set_has_pixels();
  } else {
    clear_has_pixels();
  }
  pixels_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pixels);
  // @@protoc_insertion_point(field_set_allocated:msgs.Icon.pixels)
}

// -------------------------------------------------------------------

// AppDestroyed

// required uint64 id = 1;
inline bool AppDestroyed::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppDestroyed::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppDestroyed::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppDestroyed::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 AppDestroyed::id() const {
  // @@protoc_insertion_point(field_get:msgs.AppDestroyed.id)
  return id_;
}
inline void AppDestroyed::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:msgs.AppDestroyed.id)
}

// -------------------------------------------------------------------

// AppGotFocus

// required uint64 id = 1;
inline bool AppGotFocus::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppGotFocus::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppGotFocus::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppGotFocus::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 AppGotFocus::id() const {
  // @@protoc_insertion_point(field_get:msgs.AppGotFocus.id)
  return id_;
}
inline void AppGotFocus::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:msgs.AppGotFocus.id)
}

// -------------------------------------------------------------------

// Event

// optional .msgs.AppDestroyed destroyed = 1;
inline bool Event::has_destroyed() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Event::set_has_destroyed() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Event::clear_has_destroyed() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Event::clear_destroyed() {
  if (destroyed_ != NULL) destroyed_->::msgs::AppDestroyed::Clear();
  clear_has_destroyed();
}
inline const ::msgs::AppDestroyed& Event::destroyed() const {
  // @@protoc_insertion_point(field_get:msgs.Event.destroyed)
  return destroyed_ != NULL ? *destroyed_ : *default_instance_->destroyed_;
}
inline ::msgs::AppDestroyed* Event::mutable_destroyed() {
  set_has_destroyed();
  if (destroyed_ == NULL) {
    destroyed_ = new ::msgs::AppDestroyed;
  }
  // @@protoc_insertion_point(field_mutable:msgs.Event.destroyed)
  return destroyed_;
}
inline ::msgs::AppDestroyed* Event::release_destroyed() {
  // @@protoc_insertion_point(field_release:msgs.Event.destroyed)
  clear_has_destroyed();
  ::msgs::AppDestroyed* temp = destroyed_;
  destroyed_ = NULL;
  return temp;
}
inline void Event::set_allocated_destroyed(::msgs::AppDestroyed* destroyed) {
  delete destroyed_;
  destroyed_ = destroyed;
  if (destroyed) {
    set_has_destroyed();
  } else {
    clear_has_destroyed();
  }
  // @@protoc_insertion_point(field_set_allocated:msgs.Event.destroyed)
}

// optional .msgs.Application created = 2;
inline bool Event::has_created() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Event::set_has_created() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Event::clear_has_created() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Event::clear_created() {
  if (created_ != NULL) created_->::msgs::Application::Clear();
  clear_has_created();
}
inline const ::msgs::Application& Event::created() const {
  // @@protoc_insertion_point(field_get:msgs.Event.created)
  return created_ != NULL ? *created_ : *default_instance_->created_;
}
inline ::msgs::Application* Event::mutable_created() {
  set_has_created();
  if (created_ == NULL) {
    created_ = new ::msgs::Application;
  }
  // @@protoc_insertion_point(field_mutable:msgs.Event.created)
  return created_;
}
inline ::msgs::Application* Event::release_created() {
  // @@protoc_insertion_point(field_release:msgs.Event.created)
  clear_has_created();
  ::msgs::Application* temp = created_;
  created_ = NULL;
  return temp;
}
inline void Event::set_allocated_created(::msgs::Application* created) {
  delete created_;
  created_ = created;
  if (created) {
    set_has_created();
  } else {
    clear_has_created();
  }
  // @@protoc_insertion_point(field_set_allocated:msgs.Event.created)
}

// optional .msgs.AppGotFocus got_focus = 3;
inline bool Event::has_got_focus() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Event::set_has_got_focus() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Event::clear_has_got_focus() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Event::clear_got_focus() {
  if (got_focus_ != NULL) got_focus_->::msgs::AppGotFocus::Clear();
  clear_has_got_focus();
}
inline const ::msgs::AppGotFocus& Event::got_focus() const {
  // @@protoc_insertion_point(field_get:msgs.Event.got_focus)
  return got_focus_ != NULL ? *got_focus_ : *default_instance_->got_focus_;
}
inline ::msgs::AppGotFocus* Event::mutable_got_focus() {
  set_has_got_focus();
  if (got_focus_ == NULL) {
    got_focus_ = new ::msgs::AppGotFocus;
  }
  // @@protoc_insertion_point(field_mutable:msgs.Event.got_focus)
  return got_focus_;
}
inline ::msgs::AppGotFocus* Event::release_got_focus() {
  // @@protoc_insertion_point(field_release:msgs.Event.got_focus)
  clear_has_got_focus();
  ::msgs::AppGotFocus* temp = got_focus_;
  got_focus_ = NULL;
  return temp;
}
inline void Event::set_allocated_got_focus(::msgs::AppGotFocus* got_focus) {
  delete got_focus_;
  got_focus_ = got_focus;
  if (got_focus) {
    set_has_got_focus();
  } else {
    clear_has_got_focus();
  }
  // @@protoc_insertion_point(field_set_allocated:msgs.Event.got_focus)
}

// optional .msgs.Response response = 4;
inline bool Event::has_response() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Event::set_has_response() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Event::clear_has_response() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Event::clear_response() {
  if (response_ != NULL) response_->::msgs::Response::Clear();
  clear_has_response();
}
inline const ::msgs::Response& Event::response() const {
  // @@protoc_insertion_point(field_get:msgs.Event.response)
  return response_ != NULL ? *response_ : *default_instance_->response_;
}
inline ::msgs::Response* Event::mutable_response() {
  set_has_response();
  if (response_ == NULL) {
    response_ = new ::msgs::Response;
  }
  // @@protoc_insertion_point(field_mutable:msgs.Event.response)
  return response_;
}
inline ::msgs::Response* Event::release_response() {
  // @@protoc_insertion_point(field_release:msgs.Event.response)
  clear_has_response();
  ::msgs::Response* temp = response_;
  response_ = NULL;
  return temp;
}
inline void Event::set_allocated_response(::msgs::Response* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
  // @@protoc_insertion_point(field_set_allocated:msgs.Event.response)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::msgs::Response_Status> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msgs::Response_Status>() {
  return ::msgs::Response_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2eproto__INCLUDED
